management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 1002
  servlet:
    context-path: '/book-service'

spring:
  application:
    name: book-service
  cloud:
    config:
      import-check:
        enabled: false
      uri: http://localhost:8000/config-server
  config:
    import: 'optional:configserver:'
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    #driver-class-name: org.hsqldb.jdbc.JDBCDriver
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/book-store
    username: admin
    password: 
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true      
    #generate-ddl: true  

  profiles:
    active: dev
